export const PERU_DEPARTMENTS = {
  ANCASH: [
    "LLAMELLIN",
    "PAMPAROMAS",
    "CAJACAY",
    "CANIS",
    "TICLLOS",
    "NUEVO CHIMBOTE",
    "PALLASCA",
    "TAUCA",
    "POMABAMBA",
    "SAN JUAN DE RONTOY",
    "CHACAS",
    "ACOCHACA",
    "SAN LUIS",
    "SANTIAGO DE CHILCAS",
    "LLACLLIN",
    "PAMPAS CHICO",
    "MATACOTO",
    "QUILLO",
    "RANRAHIRCA",
    "SHUPLUY",
    "HUALLANCA",
    "HUATA",
    "MATO",
    "YAUYA",
    "SANTA CRUZ",
    "SANTO TORIBIO",
    "ELEAZAR GUZMAN BARRON",
    "LLUMPA",
    "LUCMA",
    "SAN MIGUEL DE ACO",
    "SHILLA",
    "TINCO",
    "YUNGAR",
    "ANRA",
    "OCROS",
    "ACAS",
    "CONCHUCOS",
    "HUANDOVAL",
    "LLAPO",
    "SANTA",
    "ACOBAMBA",
    "HUAYLLABAMBA",
    "RAGASH",
    "SAN JUAN",
    "SICSIBAMBA",
    "BAMBAS",
    "CUSCA",
    "LA PAMPA",
    "YANAC",
    "HUANTAR",
    "MASIN",
    "RAHUAPAMPA",
    "SAN MARCOS",
    "COCHAPETI",
    "PUEBLO LIBRE",
    "CHINGAS",
    "AQUIA",
    "ACOPAMPA",
    "LA LIBERTAD",
    "CORIS",
    "HUACLLAN",
    "COISHCO",
    "HUAYLLACAYAN",
    "RECUAY",
    "MORO",
    "CHIQUIAN",
    "ABELARDO PARDO LEZAMETA",
    "COLQUIOC",
    "MANGAS",
    "INDEPENDENCIA",
    "MIRGAS",
    "CORONGO",
    "PAMPAS",
    "SANTA ROSA",
    "PAROBAMBA",
    "CASMA",
    "BUENA VISTA ALTA",
    "SAN PEDRO",
    "COTAPARACO",
    "YUNGAY",
    "CASCAPARA",
    "COLCABAMBA",
    "SAN NICOLAS",
    "YURACMARCA",
    "CASCA",
    "LLAMA",
    "BOLOGNESI",
    "HUARI",
    "CHAVIN DE HUANTAR",
    "HUACACHI",
    "HUACCHIS",
    "HUACHIS",
    "CONGAS",
    "HUACASCHUQUE",
    "LACABAMBA",
    "QUINUABAMBA",
    "CACERES DEL PERU",
    "MACATE",
    "SIHUAS",
    "CASHAPAMPA",
    "CHINGALPO",
    "QUICHES",
    "YUPAN",
    "COCHAS",
    "SUCCHA",
    "RAPAYAN",
    "CULEBRAS",
    "HUAYAN",
    "CARAZ",
    "LA MERCED",
    "ACZO",
    "CHACCHO",
    "CARHUAZ",
    "ATAQUERO",
    "MARCARA",
    "PARIAHUANCA",
    "HUARAZ",
    "HUANCHAY",
    "PARIACOTO",
    "TARICA",
    "NEPEÑA",
    "SAMANCO",
    "YAUTAN",
    "ANTONIO RAYMONDI",
    "LA PRIMAVERA",
    "PACLLON",
    "SAN MIGUEL DE CORPANQUI",
    "ACO",
    "HUAYLLAN",
    "CATAC",
    "HUAYLLAPAMPA",
    "MARCA",
    "PARARIN",
    "TAPACOCHA",
    "MANCOS",
    "YANAMA",
    "HUAYLAS",
    "PISCOBAMBA",
    "FIDEL OLIVAS ESCUDERO",
    "MUSGA",
    "CABANA",
    "COMANDANTE NOEL",
    "CAJAY",
    "CAJAMARQUILLA",
    "CARHUAPAMPA",
    "LLIPA",
    "SAN CRISTOBAL DE RAJAN",
    "CHIMBOTE",
    "ALFONSO UGARTE",
    "PAUCAS",
    "PONTO",
    "SAN PEDRO DE CHANA",
    "UCO",
    "HUARMEY",
    "MALVAS",
    "HUASTA",
    "AMASHCA",
    "ANTA",
    "COCHABAMBA",
    "JANGAS",
    "OLLEROS",
    "PAMPAS GRANDE",
    "PIRA",
    "AIJA",
    "TICAPAMPA",
  ],
  AMAZONAS: ["Test"],
  APURIMAC: ["Test"],
  AREQUIPA: ["Test"],
  AYACUCHO: ["Test"],
  CAJAMARCA: ["Test"],
  CALLAO: ["Test"],
  CUSCO: ["Test"],
  HUANCAVELICA: ["Test"],
  HUANUCO: ["Test"],
  ICA: ["Test"],
  JUNIN: ["Test"],
  "LA LIBERTAD": ["Test"],
  LAMBAYEQUE: ["Test"],
  LIMA: [
    "BARRANCA",
    "HUAURA",
    "COCHAMARCA",
    "AMBAR",
    "GORGOR",
    "LIMA",
    "MIRAFLORES",
    "MAGDALENA DEL MAR",
    "SAN LUIS",
    "SANTA ANITA",
    "SURQUILLO",
    "BREÑA",
    "SANTA ROSA",
    "LAMPIAN",
    "SAN MIGUEL DE ACOS",
    "SANTA CRUZ DE ANDAMARCA",
    "AZANGARO",
    "CARANIA",
    "HUAMPARA",
    "HUANCAYA",
    "HUANTAN",
    "LARAOS",
    "MIRAFLORES",
    "OMAS",
    "QUINOCAY",
    "SAN PEDRO DE PILAS",
    "VITIS",
    "SAN JUAN DE MIRAFLORES",
    "SANTIAGO DE SURCO",
    "VILLA EL SALVADOR",
    "EL AGUSTINO",
    "LOS OLIVOS",
    "QUILMANA",
    "HUARAL",
    "CHANCAY",
    "SUMBILCA",
    "ANTIOQUIA",
    "CALLAHUANCA",
    "HUAROCHIRI",
    "CARABAYLLO",
    "PUCUSANA",
    "PUNTA NEGRA",
    "MARIATANA",
    "SAN BARTOLOME",
    "SAN JUAN DE IRIS",
    "SAN MATEO",
    "SAN PEDRO DE HUANCAYRE",
    "SANTIAGO DE TUNA",
    "HONGOS",
    "TUPE",
    "VIÑAC",
    "ATAVILLOS BAJO",
    "CHILCA",
    "HUALMAY",
    "CACRA",
    "HUAROS",
    "CAUJUL",
    "PARAMONGA",
    "SUPE",
    "SUPE PUERTO",
    "LEONCIO PRADO",
    "YAUYOS",
    "ALIS",
    "HUANCAPON",
    "MANAS",
    "CHECRAS",
    "SANTA LEONOR",
    "CAJATAMBO",
    "COPA",
    "LURIGANCHO",
    "SAN BORJA",
    "SAN MIGUEL",
    "RIMAC",
    "INDEPENDENCIA",
    "SAN ISIDRO",
    "BARRANCO",
    "PACARAOS",
    "ALLAUCA",
    "HUAÑEC",
    "MADEAN",
    "QUINCHES",
    "TAURIPAMPA",
    "PUENTE PIEDRA",
    "SAN MARTIN DE PORRES",
    "COMAS",
    "LA MOLINA",
    "IMPERIAL",
    "SANTA CRUZ DE FLORES",
    "CARAMPOMA",
    "CHICLA",
    "HUACHUPAMPA",
    "PACHACAMAC",
    "PUNTA HERMOSA",
    "LAHUAYTAMBO",
    "RICARDO PALMA",
    "SAN MATEO DE OTAO",
    "SANGALLAYA",
    "SANTIAGO DE ANCHUCAYA",
    "SANTO DOMINGO DE LOS OLLEROS",
    "CATAHUASI",
    "CHOCOS",
    "HUANGASCAR",
    "LINCHA",
    "PUTINZA",
    "CANTA",
    "CALANGO",
    "CERRO AZUL",
    "COAYLLO",
    "NUEVO IMPERIAL",
    "SAN ANTONIO",
    "SAN LUIS",
    "ATAVILLOS ALTO",
    "AUCALLAMA",
    "SANTA MARIA DEL MAR",
    "ASIA",
    "SAN BARTOLO",
    "HUACHO",
    "CALETA DE CARQUIN",
    "SANTA MARIA",
    "LACHAQUI",
    "ANDAJES",
    "NAVAN",
    "PACCHO",
    "SAYAN",
    "VEGUETA",
    "OYON",
    "PACHANGARA",
    "PATIVILCA",
    "JESUS MARIA",
    "LINCE",
    "PUEBLO LIBRE",
    "SAN JUAN DE LURIGANCHO",
    "LA VICTORIA",
    "VEINTISIETE DE NOVIEMBRE",
    "AYAVIRI",
    "COCHAS",
    "SAN JOAQUIN",
    "TANTA",
    "TOMAS",
    "ANCON",
    "ATE",
    "CHACLACAYO",
    "VILLA MARIA DEL TRIUNFO",
    "MALA",
    "MATUCANA",
    "CUENCA",
    "HUANZA",
    "CIENEGUILLA",
    "LURIN",
    "LANGA",
    "LARAOS",
    "SAN ANDRES DE TUPICOCHA",
    "SAN ANTONIO",
    "SAN DAMIAN",
    "SAN JUAN DE TANTARANCHE",
    "SAN LORENZO DE QUINTI",
    "SAN PEDRO DE CASTA",
    "SANTA CRUZ DE COCACHACRA",
    "SANTA EULALIA",
    "SURCO",
    "ARAHUAY",
    "LUNAHUANA",
    "PACARAN",
    "ZUÑIGA",
    "IHUARI",
    "CHORRILLOS",
    "COLONIA",
    "SAN VICENTE DE CAÑETE",
    "HUAMANTANGA",
    "SAN BUENAVENTURA",
    "SANTA ROSA DE QUIVES",
    "SANTA MARIA DE HUACHIPA",
  ],
  LORETO: ["Test"],
  "MADRE DE DIOS": ["Test"],
  MOQUEGUA: ["Test"],
  PASCO: ["Test"],
  PIURA: ["Test"],
  PUNO: ["Test"],
  "SAN MARTIN": ["Test"],
  TACNA: ["Test"],
  TUMBES: ["Test"],
  UCAYALI: ["Testae"],
};
