export const PERU_DEPARTMENTS = {
  SELECCIONAR: ["SELECCIONAR"],
  AMAZONAS: [
    "CHACHAPOYAS",
    "BAGUA",
    "BONGARÁ",
    "CONDORCANQUI",
    "LUYA",
    "RODRÍGUEZ DE MENDOZA",
    "UTCUBAMBA",
  ],
  ÁNCASH: [
    "HUARAZ",
    "AIJA",
    "ANTONIO RAYMONDI",
    "ASUNCIÓN",
    "BOLOGNESI",
    "CARHUAZ",
    "CARLOS FERMÍN FITZCARRALD",
    "CASMA",
    "CORONGO",
    "HUARI",
    "HUARMEY",
    "HUAYLAS",
    "MARISCAL LUZURIAGA",
    "OCROS",
    "PALLASCA",
    "POMABAMBA",
    "RECUAY",
    "SANTA",
    "SIHUAS",
    "YUNGAY",
  ],
  APURÍMAC: [
    "ABANCAY",
    "ANDAHUAYLAS",
    "ANTABAMBA",
    "AYMARAES",
    "COTABAMBAS",
    "CHINCHEROS",
    "GRAU",
  ],
  AREQUIPA: [
    "AREQUIPA",
    "CAMANÁ",
    "CARAVELÍ",
    "CASTILLA",
    "CAYLLOMA",
    "CONDESUYOS",
    "ISLAY",
    "LA UNIÒN",
  ],
  AYACUCHO: [
    "HUAMANGA",
    "CANGALLO",
    "HUANCA SANCOS",
    "HUANTA",
    "LA MAR",
    "LUCANAS",
    "PARINACOCHAS",
    "PÀUCAR DEL SARA SARA",
    "SUCRE",
    "VÍCTOR FAJARDO",
    "VILCAS HUAMÁN",
  ],
  CAJAMARCA: [
    "CAJAMARCA",
    "CAJABAMBA",
    "CELENDÍN",
    "CHOTA",
    "CONTUMAZÁ",
    "CUTERVO",
    "HUALGAYOC",
    "JAÉN",
    "SAN IGNACIO",
    "SAN MARCOS",
    "SAN MIGUEL",
    "SAN PABLO",
    "SANTA CRUZ",
  ],
  CALLAO: [
    "CALLAO",
    "BELLAVISTA",
    "CARMEN DE LA LEGUA REYNOSO",
    "LA PERLA",
    "LA PUNTA",
    "VENTANILLA",
    "MI PERÚ",
  ],
  CUSCO: [
    "CUSCO",
    "ACOMAYO",
    "ANTA",
    "CALCA",
    "CANAS",
    "CANCHIS",
    "CHUMBIVILCAS",
    "ESPINAR",
    "LA CONVENCIÓN",
    "PARURO",
    "PAUCARTAMBO",
    "QUISPICANCHI",
    "URUBAMBA",
  ],
  HUANCAVELICA: [
    "HUANCAVELICA",
    "ACOBAMBA",
    "ANGARAES",
    "CASTROVIRREYNA",
    "CHURCAMPA",
    "HUAYTARÁ",
    "TAYACAJA",
  ],
  HUÁNUCO: [
    "HUÁNUCO",
    "AMBO",
    "DOS DE MAYO",
    "HUACAYBAMBA",
    "HUAMALÍES",
    "LEONCIO PRADO",
    "MARAÑÓN",
    "PACHITEA",
    "PUERTO INCA",
    "LAURICOCHA ",
    "YAROWILCA ",
  ],
  ICA: ["ICA ", "CHINCHA ", "NAZCA ", "PALPA ", "PISCO "],
  JUNÍN: [
    "HUANCAYO ",
    "CONCEPCIÓN ",
    "CHANCHAMAYO ",
    "JAUJA ",
    "JUNÍN ",
    "SATIPO ",
    "TARMA ",
    "YAULI ",
    "CHUPACA ",
  ],
  "LA LIBERTAD": [
    "TRUJILLO ",
    "ASCOPE ",
    "BOLÍVAR ",
    "CHEPÉN ",
    "JULCÁN ",
    "OTUZCO ",
    "PACASMAYO ",
    "PATAZ ",
    "SÁNCHEZ CARRIÓN ",
    "SANTIAGO DE CHUCO ",
    "GRAN CHIMÚ ",
    "VIRÚ ",
  ],
  LAMBAYEQUE: ["CHICLAYO ", "FERREÑAFE ", "LAMBAYEQUE "],
  LIMA: [
    "LIMA ",
    "BARRANCA ",
    "CAJATAMBO ",
    "CANTA ",
    "CAÑETE ",
    "HUARAL ",
    "HUAROCHIRÍ ",
    "HUAURA ",
    "OYÓN ",
    "YAUYOS ",
  ],
  LORETO: [
    "MAYNAS ",
    "ALTO AMAZONAS ",
    "LORETO ",
    "MARISCAL RAMÓN CASTILLA ",
    "REQUENA ",
    "UCAYALI ",
    "DATEM DEL MARAÑÓN ",
    "PUTUMAYO",
  ],
  "MADRE DE DIOS": ["TAMBOPATA ", "MANU ", "TAHUAMANU "],
  MOQUEGUA: ["MARISCAL NIETO ", "GENERAL SÁNCHEZ CERRO ", "ILO "],
  PASCO: ["PASCO ", "DANIEL ALCIDES CARRIÓN ", "OXAPAMPA "],
  PIURA: [
    "PIURA ",
    "AYABACA ",
    "HUANCABAMBA ",
    "MORROPÓN ",
    "PAITA ",
    "SULLANA ",
    "TALARA ",
    "SECHURA ",
  ],
  PUNO: [
    "PUNO ",
    "AZÁNGARO ",
    "CARABAYA ",
    "CHUCUITO ",
    "EL COLLAO ",
    "HUANCANÉ ",
    "LAMPA ",
    "MELGAR ",
    "MOHO ",
    "SAN ANTONIO DE PUTINA ",
    "SAN ROMÁN ",
    "SANDIA ",
    "YUNGUYO ",
  ],
  "SAN MARTÍN": [
    "MOYOBAMBA ",
    "BELLAVISTA ",
    "EL DORADO ",
    "HUALLAGA ",
    "LAMAS ",
    "MARISCAL CÁCERES ",
    "PICOTA ",
    "RIOJA ",
    "SAN MARTÍN ",
    "TOCACHE ",
  ],
  TACNA: ["TACNA ", "CANDARAVE ", "JORGE BASADRE ", "TARATA "],
  TUMBES: ["TUMBES ", "CONTRALMIRANTE VILLAR ", "ZARUMILLA "],
  UCAYALI: ["CORONEL PORTILLO ", "ATALAYA ", "PADRE ABAD ", "PURÚS"],
};
